### PR TITLE
feat: add build command

### PR DESCRIPTION
**Pull request by jquense**

### CODE REVIEW

**Comment by jquense** [comment]
thoughts?

**Comment by itajaja** [comment]
this in practice will just substitute the `build` entry in package.json commands?

**Comment by taion** [comment]
i think this just saves some typing there? sounds good to me

**Comment by jquense** [comment]
yup fairly uncontroversial i think, saves typing and hopefully prevents some config issues. it also means we can remove babel-cli from deps, babel-core always stays because peer dependencies are an evil that seems to need to exist

**Pull request merged**
