### PR TITLE
fix: Fail on not making commit

### PR DESCRIPTION
**Pull request by taion**
Otherwise we end up tagging the wrong commit.

### CODE REVIEW

**Comment by taion** [comment]
got some weirdness here running this on a package without conventional commits

**Comment by jquense** [comment]
The issue is that publishing without needing to bump the pkg.json version will break, since no commit is produced. It's not super common but happens

**Comment by taion** [comment]
@jquense couldn't we just do `--skip-git` in that case? like, wouldn't that be the correct thing to do?

**Comment by taion** [comment]
the problem is that, without error handling, i hit a case in a repo without a changelog where the git commit/&c. failed, so i got the tag attached to the pre-version-bump commit in github

**Comment by jquense** [comment]
`--skip-git` is probably fine, but it failed poorly, maybe we should fail and tell the user? idk it's not a big deal

**Comment by taion** [comment]
@jquense isn't "not catching the error here" doing just that, w/r/t failing and telling the user?

**Comment by jquense** [comment]
sure to some degree.

**Pull request merged**
